# Generated by Django 5.1 on 2024-09-01 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('describe_user', models.CharField(blank=True, max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_country', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_birthday', models.DateField()),
                ('user_image', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('user_cover', models.ImageField(blank=True, upload_to='cover_pics/')),
                ('user_reg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('posts', models.IntegerField(default=0)),
                ('recovery_account', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
