# Generated by Django 5.1 on 2024-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='describe_user',
            field=models.CharField(default='Hello Coding Cafe. This is my default status!', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='recovery_account',
            field=models.CharField(default='Iwanttoputadingintheuniverse', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
