# Generated by Django 5.1 on 2024-09-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_describe_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_pass',
        ),
    ]
