# Generated by Django 5.1 on 2024-09-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagepost/'),
        ),
    ]
