# Generated by Django 5.1 on 2024-09-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_post_user_id_alter_post_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
