# Generated by Django 5.1 on 2024-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_cover',
            field=models.ImageField(default='cover_pics/default_cover.jpg', upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/'),
        ),
    ]
