# Generated by Django 5.1 on 2024-09-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/'),
        ),
    ]
