# Generated by Django 5.1 on 2024-09-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='posts',
            field=models.BooleanField(default='0'),
        ),
    ]
