# Generated by Django 5.1 on 2024-09-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='recovery_account',
            new_name='recovery_answer',
        ),
    ]
