# Generated by Django 5.1 on 2024-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_recovery_account_userprofile_recovery_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recovery_answer',
            field=models.CharField(blank=True, default='Iwanttoputadingintheuniverse', max_length=255, null=True),
        ),
    ]
