# Generated by Django 5.1 on 2025-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_recovery_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='describe_user',
            field=models.CharField(default='Hello Codebook. This is my default status!', max_length=255),
        ),
    ]
